export CUR=$PWD . 
cp ~/bin/apk_time_rank.sh . 
cp ~/bin/AppData . 
cp ~/bin/Apps . 
cp ~/bin/bayvictor_gitconfig.sh . 
cp ~/bin/clean_all_AndroidManifest.xml.sh . 
cp ~/bin/clean_make_all.2013-09-03-18-44-19.log.txt . 
cp ~/bin/Client.ico . 
cp ~/bin/cnfn.sh . 
cp ~/bin/compile_py_with_tcl_tk.sh . 
cp ~/bin/Config.xml . 
cp ~/bin/Deployment . 
cp ~/bin/desktop.ini . 
cp ~/bin/developer-guide.html . 
cp ~/bin/Devices.xml . 
cp ~/bin/diff_srp-1.3_last_orig.log.txt . 
cp ~/bin/diff_trial_trial02.log.txt . 
cp ~/bin/diff.trial.txt . 
cp ~/bin/diskbackup_hw_dell . 
cp ~/bin/down_py353.sh . 
cp ~/bin/Drivers.xml . 
cp ~/bin/du-h_home_vhuang.txt . 
cp ~/bin/fstim_all_sda_n.sh . 
cp ~/bin/geckodriver . 
cp ~/bin/get_nvidia_driver_sourcecode.sh . 
cp ~/bin/git_add_push_all.sh . 
cp ~/bin/github_down_nvidia_drivers.sh . 
cp ~/bin/github_redown_rankings.sh . 
cp ~/bin/github_syncall.sh . 
cp ~/bin/github_update_all.sh . 
cp ~/bin/.gpackdir.swp . 
cp ~/bin/gziphead . 
cp ~/bin/idea-generator.git . 
cp ~/bin/index_w_jieba.py . 
cp ~/bin/ins_boost_4_k3d.sh . 
cp ~/bin/install_py361_under1404_1604.sh . 
cp ~/bin/jake_setup.sh . 
cp ~/bin/make_all_subdir_pdf2txt_to_dir.sh . 
cp ~/bin/prepare_py27.sh . 
cp ~/bin/Product.xml . 
cp ~/bin/publication-digest.txt . 
cp ~/bin/REAdEME.txt . 
cp ~/bin/README.md . 
cp ~/bin/redown_L1_github_repo.sh . 
cp ~/bin/Resources . 
cp ~/bin/runecho.sh . 
cp ~/bin/setup_matplot.sh . 
cp ~/bin/setup_tesseract.sh . 
cp ~/bin/subdir_all_pdf2txt_uptodir_dotdot_pdf2txt.py . 
cp ~/bin/subdir_cpall_txt_to_dir.py . 
cp ~/bin/subdir_find_build.xml_n_build.py . 
cp ~/bin/subdir_git_syncall.sh . 
cp ~/bin/subdir_level1_tag_github_syncall.sh . 
cp ~/bin/subdir.pdf2txt.py . 
cp ~/bin/subdir_scan_AndroidManifest.xml_n_update_config.py . 
cp ~/bin/sunpinyin_2.0.3+git20120607.orig.tar.xz . 
cp ~/bin/sync_all.sh . 
cp ~/bin/tarbig . 
cp ~/bin/test012.txt . 
cp ~/bin/test.txt . 
cp ~/bin/ubu1404.5_gpg_keys.sh . 
cp ~/bin/ubu_geckodriver.sh . 
cp ~/bin/ubu_nodejs_setup.sh . 
cp ~/bin/uninstaller.bat . 
cp ~/bin/Uninstaller.exe . 
cp ~/bin/Uninstaller.manifest . 
cp ~/bin/unzip . 
cp ~/bin/UpdatedConfig.xml . 
cp ~/bin/up_win7_sda1_under_ubu.sh . 
cp ~/bin/Users . 
cp ~/bin/victor-qt5.9-configure . 
cp ~/bin/vmware-serial-number.txt . 
cp ~/bin/win7.apps.ini . 
cp ~/bin/y=Wx+b.py . 
cp ~/bin/zipall.sh . 
