git add README.md
git add y=Wx+b.py
git add victorrun.sh
git add go.sh
git add setup_nginx.sh
git add wechaty-run.sh
git add bin
git add bin/download_android.src.sh
git add bin/subdir.pdf2txt.py
git add bin/unmount_all.sh
git add bin/build_all_efl_batch02__from_scratch.sh
git add bin/django_get_satchimo.sh
git add bin/allnic.sh
git add bin/ubu_inst_hadoop.sh
git add bin/copy_subdir_shell_files_to__bin__dir.sh
git add bin/subdirquickx86.sh
git add bin/subdir_shorten_fn.sh
git add bin/manual_mount_all_UUID.sh
git add bin/bandwidth_throttle.sh
git add bin/Building_Qt_5_from_Git.sh
git add bin/install_maemo5_sdk.sh
git add bin/setup_htc_android.sh
git add bin/runecho.sh
git add bin/bashrc_dell7710
git add bin/setopt
git add bin/adb_list_apks.sh
git add bin/README.md
git add bin/preinstall_qt5.sh
git add bin/largefiles_in_GB.sh
git add bin/add-nwe-upnp-service-on-phone02.sh
git add bin/gen_firefox_profile_batch_launcher.sh
git add bin/aptget_ssh_n_copyid.sh
git add bin/curdir_unzip.sh
git add bin/apt.sh
git add bin/etc_networks.orig
git add bin/wget_gdbserver.sh
git add bin/make_redmine_partition_img.sh
git add bin/libxml2_2.9.0+dfsg1-4ubuntu4.3.dsc
git add bin/maven_eclipse.sh
git add bin/build-chromium-with-runhooks.sh
git add bin/CodeSourcery_setup.sh
git add bin/test.sh
git add bin/wget_hi5_id_profiles.sh
git add bin/setup_android_in_ubu201610.sh
git add bin/setup_fcitx-googlepinyin.sh
git add bin/repl_all_subdir_oldstr_newstr.sh
git add bin/dd_clone_disk_progress.sh
git add bin/get_filenamelist__excl_bin__given_keyword.sh
git add bin/get_nvidia_driver_sourcecode.sh
git add bin/sb2build.sh
git add bin/ls_all_trimable_fs.sh
git add bin/clean_makeall.sh
git add bin/html2text.py
git add bin/howto_install_apps_from_getdeb.sh
git add bin/inputs.json
git add bin/install_redmine_20130701.sh
git add bin/gen_backup_domain_list.sh
git add bin/find_then_replace_filename_keyword_w_newword.py
git add bin/droidtag.sh
git add bin/run_jenkins_on_port.sh
git add bin/pre-qt-scratchbox.sh
git add bin/clingmv__to_lib_standalone_n_lib_jar.sh
git add bin/autoconf_2.69-1ubuntu1.dsc
git add bin/test0001.txtcat
git add bin/up_win7_sda1_under_ubu.sh
git add bin/github_upload.sh
git add bin/preinstall_k3d.sh
git add bin/gen_all_mozilla_cookies.txt_from_profiles.sh
git add bin/ins_all_ntfs_facilities.sh
git add bin/unrar_all_splited_rar.sh
git add bin/gen_manual_mount_dev_batch.sh
git add bin/ins_lvm2.sh
git add bin/ins_bugzilla_plugins.sh
git add bin/gsettings_gedit_gb.sh
git add bin/remove_only_mysql.sh
git add bin/phone_vncviewer.sh
git add bin/ubuntu1404_sandbox_cloudify_jason.sh
git add bin/docker_run_ubu14.04.sh
git add bin/r74789-enable-all-build-chromium-with-runhooks.sh
git add bin/setup_matplot.sh
git add bin/compile_py_with_tcl_tk.sh
git add bin/x86_quick_make_all.sh
git add bin/unzip_rpm.sh
git add bin/command_line_android_create_project.sh
git add bin/ubu_setup_svn_server.sh
git add bin/compile_with_mysql.sh
git add bin/android_setup.sh
git add bin/toolchain_usecase02.sh
git add bin/normalilze_curdir_txt_format_name.sh
git add bin/wf2pydict.sh.wfswap
git add bin/copy_raw_dvd.sh
git add bin/clone_dir_frame
git add bin/uninstaller.bat
git add bin/apt_get_all.sh
git add bin/cleanupall.sh
git add bin/reset_xfinity_cable_modem_Motorola_SB6120.sh
git add bin/samba_setup.sh
git add bin/cp_srcdir_apk_to_curdir.sh
git add bin/subdir_all_pdf2txt_uptodir_dotdot_pdf2txt.py
git add bin/ln_sda8_subdir_to_home.sh
git add bin/up_n_running_tightvncserver.sh
git add bin/gen_backup_latest_n_dir.sh
git add bin/ln_home_all.sh
git add bin/gterm
git add bin/run_joy_example.sh
git add bin/mv_large_out.sh
git add bin/filelist_contain_keyword.sh
git add bin/install-all.sh
git add bin/cloudify_nodecellar_example_fix_requests_less_error.sh
git add bin/install_ffmpeg.sh
git add bin/runeclipse.sh
git add bin/ime_config_fcitx.sh
git add bin/rackup.bat
git add bin/androidd
git add bin/wget_apt-get_setup_vmserver.sh
git add bin/gen_der_from_pem.sh
git add bin/ok_subdir_html2txt.py
git add bin/preinstall_32libs.sh
git add bin/x86set
git add bin/install_vmware_server_on_ubuntu.sh
git add bin/headfix.sh
git add bin/build-lighthouse-git-2010-11-10-05-22-05.sh
git add bin/manual_mount_all_raids.sh
git add bin/find_build.xml_and_ant_debug.sh
git add bin/dum
git add bin/~?.bashrc
git add bin/rebuild_ok_apk_timestamping_appname.sh
git add bin/newtorid
git add bin/convert_dd_image_to_vdi.sh
git add bin/swapcolumn.sh
git add bin/wwget
git add bin/min_configure_chromium.sh
git add bin/bugzilla_bugzilla-4.2.1_contrib_new-yui.sh
git add bin/quick_make_all.sh
git add bin/preinstall_32libs_for_lighthouse.sh
git add bin/ubuntu_sshd_install.sh
git add bin/fix_testparm_error_in_samba.sh
git add bin/autokeys.sh
git add bin/wordlist_googsrc.py
git add bin/init_sshfs_on_remote_host.sh
git add bin/all_fcitx.sh
git add bin/install_tizen.sh
git add bin/test_bugzilla.sh
git add bin/gbgo.sh
git add bin/refresh_initramfs.sh
git add bin/install_homebrew.sh
git add bin/y=Wx+b.py
git add bin/ubu_nodejs_setup.sh
git add bin/scratchbox_init_afer_untar.sh
git add bin/emacs_config
git add bin/hi5.txt.sh
git add bin/gen_github_down_script.sh
git add bin/install_python_tree_ete2.sh
git add bin/sources.list
git add bin/install_ubuntu_phpmyadmin.sh
git add bin/subdir_mvn_install.sh
git add bin/run_samjava.sh
git add bin/ins_qt4-qtruby.sh
git add bin/uninstall_redmine.sh
git add bin/subdir_shareall.sh
git add bin/find_timestamp_desc.sh
git add bin/last_redmine.sh
git add bin/gpu_benchmark.sh
git add bin/install_android_src.sh
git add bin/googleearth
git add bin/init-sid-mameo.sh
git add bin/makesubdir.sh
git add bin/up.sh
git add bin/echo_usb.sh
git add bin/cagithub.sh
git add bin/top_n_word_out_of_box.py
git add bin/rbenv-setup.sh
git add bin/split_big_translation_script_n_run.sh
git add bin/gitpyvcloud.sh
git add bin/Config.xml
git add bin/trusty_install_puppetlabs_openstack.sh
git add bin/gitclonejenkins.sh
git add bin/UpdatedConfig.xml
git add bin/HEAD
git add bin/apacherr
git add bin/r78965-enable-all-build-chromium-with-runhooks.sh
git add bin/git_plm.sh
git add bin/install.essentials.sh
git add bin/aptget_devstack.sh
git add bin/install-all02.sh
git add bin/aptget_build_essentials_etc.sh
git add bin/qmake2cmake.rb
git add bin/wafgo.sh
git add bin/install_imake.sh
git add bin/init_upnpbrowser.sh
git add bin/get-pip.py
git add bin/setup-for-using-gold.sh
git add bin/setup_logstash.sh
git add bin/compile_qt5.sh
git add bin/aliases
git add bin/sshfs_on_E63201.sh
git add bin/killproc.py
git add bin/all_redmine.sh
git add bin/upnp_service__call_migrate_added_on_phone.sh
git add bin/gowall.sh
git add bin/lower_level_format_driver_c.sh
git add bin/lsbig.sh
git add bin/pdf2txt_with_python-pdfminer.py
git add bin/subdir_html2txt.py
git add bin/zoicbox_divided_curdir_stackedGenerator.sh
git add bin/setup__logstash_and_kibana_to_centralize_logs_on_ubuntu14.04.sh
git add bin/maven_setup.sh
git add bin/stream_down_tweets.sh
git add bin/victorrun.sh
git add bin/get_gitosis_src.sh
git add bin/resolv.conf
git add bin/proxy_through_tor.sh
git add bin/setup_tesseract.sh
git add bin/mkdir_mount_points.sh
git add bin/mv_sudirfiles_here.sh
git add bin/smb.conf
git add bin/get_plugins_from_zoic_ui_form.sh
git add bin/run_mindcraft_client.sh
git add bin/install-n-build-qt5beta.sh
git add bin/setup__logstash_and_kibana_to_centralize_logs_on_ubuntu14.04_opt02.sh
git add bin/refresh_all_adword_csv_filename_with__timestamp_uuid.sh
git add bin/bintar.sh
git add bin/prehadoop.sh
git add bin/add_root_gui.sh
git add bin/init_lamp.sh
git add bin/github_down_git.py
git add bin/wordlist_googim.py
git add bin/setup_yum.sh
git add bin/subdir_scan_AndroidManifest.xml_n_update_config.py
git add bin/new_setup_samba.sh
git add bin/wget_latest_libxml2.sh
git add bin/get_android_eclipse_bundle_1inall.sh
git add bin/NEWVICTOR_MARK
git add bin/apt-cache-missing-packs.sh
git add bin/svnrepos_conf_passwd
git add bin/keep_order_uniq_w1.py
git add bin/tar_all_upnp_code.sh
git add bin/ubuntu_install_ant.sh
git add bin/go.sh
git add bin/android
git add bin/apt-get-collada.sh
git add bin/ndkinit.sh
git add bin/get_all_codeSourceryGcc.sh
git add bin/init_icepy.sh
git add bin/install_mingw_for_win32_target_cross-compiler.sh
git add bin/internalization_setup.sh
git add bin/conf_pile_outside.sh
git add bin/find_all_pro_and_append_lines.py
git add bin/raspberryPi_toolchain_setenv.sh
git add bin/enable_root_gui_login.sh
git add bin/openssl_1.0.1c-4ubuntu8.1.dsc
git add bin/mount_all_sshfs_on_dell7710.sh
git add bin/uic_wordfreq.sh
git add bin/cassandra_setup.sh
git add bin/install_lvm2.sh
git add bin/howto_install_redmine_212_in_ubuntu_1210_and_apache_passenger.sh
git add bin/git_qtwebkit_gardening.sh
git add bin/get_libs_arg.sh
git add bin/cp_apk_to_curdir.sh
git add bin/cloudify_nodecellar_example_bs_cloudstack_vpc_blueprint.sh
git add bin/flash_roms__into_dir.sh
git add bin/preinstall_qtsdk4.7.sh
git add bin/install_stratus.sh
git add bin/Encrypt_Partition_under_Ubuntu_11.10.sh
git add bin/ubu_install_ed2k.sh
git add bin/home_vhuang_Downloads_linphone-3.3.2_compiled_ok.go.sh
git add bin/gen_github_downscript_from_txt.sh
git add bin/aptget_srp_depending_src.sh
git add bin/setup_sane__for_scanner.sh
git add bin/#setup_lighthouse.sh#
git add bin/ubuntu_pdf_install.txt.sh
git add bin/chinese_filename_support.sh
git add bin/apt-get-gpt-utilities.sh
git add bin/job_dragonboard__wget__androidBoard___patchs_n_build_it.txt.sh
git add bin/install_rampart.sh
git add bin/job_git-commit-all-for-1st-time.sh
git add bin/rescript_commoncrawler_defectfiles.sh
git add bin/ubuntu1404_sandbox_cloudify_manager_cloudify_manager_blueprints_bootstrapall.sh
git add bin/home_vhuang_Downloads_ekiga-3.2.7.go.sh
git add bin/_version.properties
git add bin/dd_if_of__diskclone.sh
git add bin/unrar_all.sh
git add bin/reset02_xfinity_cable_modem_Motorola_SB6120.sh
git add bin/wget_gcc.sh
git add bin/setup_nginx.sh
git add bin/mozc_1.6.1187.102-1~quantal1.dsc
git add bin/go30x86.sh
git add bin/curdir_dig_gitall_from_html.sh
git add bin/compile_glib.sh
git add bin/test_wget_with_tor.sh
git add bin/dirnorm.py
git add bin/filter_out_num_hi5_id_from_any_txt.sh
git add bin/get_fresh_cling_r7.sh
git add bin/clean_all_AndroidManifest.xml.sh
git add bin/lowercase.sh
git add bin/tarbig
git add bin/do.sh
git add bin/all_curdir_csv_to_dict.sh
git add bin/rdesk114.sh
git add bin/install_src_mediatomb.sh
git add bin/all_mount_once.sh
git add bin/install_ubuntu_desktop_in_ubuntu_server_without_internet_with_alternate_CD.sh
git add bin/fix_libuuid.sh
git add bin/clone_hosts_file_over.sh
git add bin/pull_bluescape_thoughtstream.sh
git add bin/ln_samba_root
git add bin/sogou-matlab-setup.sh
git add bin/setup_rhomobile.py
git add bin/wget_glib218_214.sh
git add bin/create_new_docker-machine.sh
git add bin/install_xfs.sh
git add bin/bugzilla_postgres_apt_get.sh
git add bin/browser-upnp-build.sh
git add bin/setup_maemo_scratchbox_hathor.sh
git add bin/preinstall_redmine.sh
git add bin/jpg2pdf.sh
git add bin/update_sogou_ubuntu_dicts.sh
git add bin/oneliner.py
git add bin/nexus_installer_on_ubuntu.sh
git add bin/ddrescue_clone_in_fault_tolerant_way-02.sh
git add bin/install_docker.sh
git add bin/change_uuid_of_dev_sdax.sh
git add bin/201205_install_github_server.sh
git add bin/all481.sh
git add bin/Client.ico
git add bin/subdir_ziplist.sh
git add bin/install_py361_under1404_1604.sh
git add bin/kill_ps_has_keyword.sh
git add bin/qt.conf
git add bin/find_flashable_apk.sh
git add bin/gsoap_2.8.7-2.dsc
git add bin/imagemagick-tool-sougou-etc.sh
git add bin/install_evolution.sh
git add bin/build_win32_on_linux.sh
git add bin/mvall_ls_lt.sh
git add bin/install_java8_ELK.sh
git add bin/lvm_jobs.sh
git add bin/redown_L1_github_repo.sh
git add bin/gz2bz2_via_efficient_pipe.sh
git add bin/cyg_pip_inst_stchm.bat
git add bin/mmap_err-fix-3_lines_of_vm.vdso_n_net.ipv4_in__etc_sysctl.conf_fix_mmap__no_such_device_or_address.sh
git add bin/wget_n_build_arm_liblz.sh
git add bin/genlist_ls_ltr.sh
git add bin/README.htm
git add bin/pinyinsetup.sh
git add bin/reinstall_grub.sh
git add bin/aptcache2get.sh
git add bin/sort_len.word_desc.py.sh
git add bin/apport_build.sh
git add bin/resort_list_tailed_old_ordernum.sh
git add bin/golang_setup.sh
git add bin/wget_solr42.sh
git add bin/description
git add bin/cross-compile-arm-x86-sb2-cross-ng.sh
git add bin/armmakesubdir.sh
git add bin/gitpull.sh
git add bin/bash_profile__macbook
git add bin/aptget_sb2.sh
git add bin/mountall.sh
git add bin/wf2pydict.sh.swap
git add bin/build_all_pro_under_subdir.sh
git add bin/prepare_py27.sh
git add bin/normlist.sh
git add bin/cpan_auto_with_cpanm.sh
git add bin/r78529-enable-all-build-chromium-with-runhooks.sh
git add bin/subdir_cpall_txt_to_dir.py
git add bin/apt-get.sh
git add bin/tree_1.6.0-1.dsc
git add bin/glusterfs-setup.sh
git add bin/init_bugzilla.sh
git add bin/wget_glib2.sh
git add bin/pptx2txt.sh
git add bin/fstim_all_sda_n.sh
git add bin/subdir_github_unzip_make_apk.sh
git add bin/Makefile_CFLAG
git add bin/github_down0.py
git add bin/setup_ssh-server_ubuntu.sh
git add bin/subdir_repl.sh
git add bin/make.w1.filter.stopword.sh
git add bin/ins_virtualbox.sh
git add bin/sudoers
git add bin/configure-qt-everywhere-opensource-src-4.7.1.sh
git add bin/dragonboard__wget__androidBoard___patchs_n_build_it.txt.sh
git add bin/install_pinax_093.sh
git add bin/rename_all.sh
git add bin/ubu_geckodriver.sh
git add bin/set_virtualbox_vm.sh
git add bin/gen_lombok_android.sh
git add bin/dual_static_n_so_build.sh
git add bin/ceph_preflight.sh
git add bin/config_kdeutils.sh
git add bin/value_strings.xml_list.sh
git add bin/convert_xp_to_vmdk.sh
git add bin/kill_all_wget.sh
git add bin/repl_sdi_sdh.sh
git add bin/-fr
git add bin/ubuntu_install_ansible.sh
git add bin/make_ui2html_batchlist.sh
git add bin/ca_gitconfig.sh
git add bin/docker-pid
git add bin/div_group_adwords.py
git add bin/init_sshfs_mount.sh
git add bin/github_redown_rankings.sh
git add bin/ins_nfs.sh
git add bin/ubuntu_aspire_nosound_resolve.sh
git add bin/index2gitall.sh
git add bin/setup_ubu1410__after_installation.sh
git add bin/backall.sh
git add bin/build_share_qt.sh
git add bin/make_all_ssfs_for_outsiders.sh
git add bin/aptsrc.sh
git add bin/install_node.js.sh
git add bin/ins_eclipse_pac.sh
git add bin/nexus7_driver.sh
git add bin/html5-editor-gwrite-setup.sh
git add bin/build_cvs_server2.sh
git add bin/wechaty-run.sh
git add bin/runme_only_once_to_jumpstart.sh
git add bin/nosudo_go.sh
git add bin/git_pack.sh
git add bin/wrap_raw_url_into_htmllinks.sh
git add bin/tarin
git add bin/mouse_over__sdl_setup.sh
git add bin/setup_i18n.sh
git add bin/outdirx86clean_build.sh
git add bin/gen_activity_for_java_in_dir.sh
git add bin/build_chromeOs.sh
git add bin/resolv.conf.backup
git add bin/bin
git add bin/ubuntu_hyperterminal.sh
git add bin/geoip.sh
git add bin/android_libz_not_found_lib32_problem.sh
git add bin/setup_lighthouse.sh
git add bin/checkin_qextserialport.sh
git add bin/succeed_in_ubu_setup_mediatomb.sh
git add bin/subdir_createdownframe.sh
git add bin/all_addaptrepo.sh
git add bin/init_openstack.sh
git add bin/refresh_fstab_with_uuid_boot.sh
git add bin/ramBootOnlyDragonBoard.sh
git add bin/remove_default_Java_instalation_in_Ubuntu_10.10_and_using_Sun_Java_6_for_investment.sh
git add bin/backup.log
git add bin/makeupper.sh
git add bin/curdir_normalize_filename.sh
git add bin/git_accounts-sso.sh
git add bin/ln_new_home_to_bigdisk.sh
git add bin/change_uuid_of_drive.sh
git add bin/dump_cookies_from_chrome__v19.sh
git add bin/pyskype.py
git add bin/Setup_a_Subversion_Server_in_4_Minutes.sh
git add bin/cbuild
git add bin/dd_diskclone_progress.sh
git add bin/subdir_okapk_relativepaths_in_norm.sh
git add bin/ubu14.04_install_openstack.sh
git add bin/post_openport_in_CentOs.sh
git add bin/x86_new_clean_makeall.sh
git add bin/makearm.sh
git add bin/sshfs_on_v115.sh
git add bin/top_n_word_out_of_box02.py
git add bin/nvm.sh
git add bin/down_3packages.sh
git add bin/up_v102_sshfs.sh
git add bin/mount_all_large_remote_disks.sh
git add bin/install_googledrive.sh
git add bin/cisco_openstack_installer.sh
git add bin/ramBootOnly.sh
git add bin/setup_pinax_201112.sh
git add bin/build_tina.sh
git add bin/init_pdb.sh
git add bin/subdir.normalize.cnfilename.py
git add bin/clone_disk_with_dd_bs=10M.sh
git add bin/qtable_list_for_zoicbox.sh
git add bin/build_gradle_dobatch.sh
git add bin/dirclean_baidu_upload.sh
git add bin/predrone_setup.sh
git add bin/restart_samba.sh
git add bin/build_MeeGo_Qemu.sh
git add bin/torrc
git add bin/zipall_subdir.sh
git add bin/wget_pybugz.sh
git add bin/desktop.ini
git add bin/ins_autofs.sh
git add bin/emails_in_file.py
git add bin/batch_repl.sh
git add bin/dir_batch_map2gitproject.sh
git add bin/ubuntu14.04_nosound.sh
git add bin/mvall_goo_down_from_ssd_to_hd.sh
git add bin/install_jdk_jre_java.sh
git add bin/repl_all_pending_link_in_list.sh
git add bin/github_down.old.py
git add bin/bashrc_macbook
git add bin/install_centos_phpmyadmin.sh
git add bin/install_whole_family_on_keyword.sh
git add bin/ln_sdax_home_vhuang_here.sh
git add bin/wordfreq_lowercase
git add bin/Grabserial-1.5.0
git add bin/ppt2txt.sh
git add bin/cloudify_nodecellar_example_go.sh
git add bin/symbolic_etags_file_ext
git add bin/new_all_redmine.sh
git add bin/disable_screensaver.sh
git add bin/setup_ubuntu_14.04.sh
git add bin/behead_his.sh
git add bin/all_in_all.sh
git add bin/resolve_adb_libstdc_error.sh
git add bin/install_all_llvm.sh
git add bin/subdir_make_apk.py
git add bin/linkedin_norm
git add bin/clean_make_all.sh
git add bin/wordlist2github_down_script.sh
git add bin/install_all_adwords.sh
git add bin/libevent_2.0.19-stable-3.dsc
git add bin/up_all_hi5_pets_from_copy_paste_txt.sh
git add bin/armconf
git add bin/cloudify_nodecellar_example_bootstrap_all.sh
git add bin/linkedin_cat
git add bin/ins_pyqt.sh
git add bin/rmi_docker_dup.py
git add bin/qt484-configure
git add bin/.emacs
git add bin/curdir_cp_downthemall_filename_to_newdir_with_shorten_name.py
git add bin/subdir_update_all_git.sh
git add bin/grepemail.sh
git add bin/numhead_renorm.sh
git add bin/setcolor.sh
git add bin/generate_manual_UUID_mount_all_script.sh
git add bin/tar.bz2-to-tgz_via_efficient_pipe.sh
git add bin/gen_private_der_from_pem.sh
git add bin/apacess
git add bin/pass_env_to_docker.sh
git add bin/gbk2utf.sh
git add bin/backup_all_to_3T01.sh
git add bin/plm_install-all-bugzilla3_n_4-02.sh
git add bin/dpkg_force-post_apt-get.sh
git add bin/all_setup_ssh.sh.save
git add bin/cygwin_subdir_do__AndroidManifest.py
git add bin/arm-conf-n-build-chromium.sh
git add bin/apt_yacc_flex_src.sh
git add bin/setup_magnifier.sh
git add bin/mygeoip.sh
git add bin/install-all.sh-03
git add bin/install-all03.sh
git add bin/binds_aof_sshfs.sh
git add bin/wget_bugzilla.sh
git add bin/rmi_all_none_tag.sh
git add bin/ln_s_sda2_to_home.sh
git add bin/victor_dig_email.sh
git add bin/hi5_subdir_html2csv.py
git add bin/aptcachtoget.sh
git add bin/install_mingw__for_building_win32_from_linux.sh
git add bin/bashrc
git add bin/aptget_maven_ant.sh
git add bin/cvs_server_init.sh
git add bin/digout_cnet_down_app_url.sh
git add bin/setup_bzr_localserver.sh
git add bin/batch_launch_chrome_multitab_for_hi5_id_list_from_txtfile.sh
git add bin/qt5-configure
git add bin/testphp.php
git add bin/cookies_sqlite2txt.py
git add bin/stelvio_gen_setting.gradle.sh
git add bin/setup_codesourcery.sh
git add bin/w1freqge3.sh
git add bin/ubuntu_update_firefox_from_repo.sh
git add bin/cnet_android_top_n_down.sh
git add bin/install-all-evolution.sh
git add bin/csv_sort_on_field_number.sh
git add bin/install_all_generated_ffmpeg_libraries.sh
git add bin/install_hathon_scratchbox_from_sources.list.sh
git add bin/sync_8engine_src.sh
git add bin/ubu_general_ins.sh
git add bin/createdownframe
git add bin/rdesk2.sh
git add bin/install_all_qt4.sh
git add bin/all_sshfs_mount.sh
git add bin/pptx2txt_oneliner.sh
git add bin/startover.sh
git add bin/ins_ruby_qt_binding.sh
git add bin/make_all_subdir_pdf2txt_to_dir.sh
git add bin/github_down_nvidia_drivers.sh
git add bin/wf2pydict.sh.dict.py
git add bin/dirwf
git add bin/ubu_setup_emule.sh
git add bin/pip_curdir_requirements.txt.sh
git add bin/putup
git add bin/all_firefox_profile.sh
git add bin/cgsi-gsoap_1.3.5-1.dsc
git add bin/limit_bandwidth.sh
git add bin/install_mx330_64bit2013.sh
git add bin/tor_build_ins_from_src.sh
git add bin/backjars.sh
git add bin/ubu_video_setup.sh
git add bin/bash_profile_macbook
git add bin/gitclone_pyvcloud_cloudify-docker-plugin.sh
git add bin/aptseek.sh
git add bin/Installing_and_configuring_Trac_and_Subversion_on_squeeze.sh
git add bin/wget_ndk-r8e.sh
git add bin/raid.sh
git add bin/apt-get-hfsplus.sh
git add bin/add_all_apt-get_sources.list_keys.sh
git add bin/fast_etag_.h.cpp.files_contains.iostream.h__.sh
git add bin/curdir_ndk_build.sh
git add bin/tag.sh
git add bin/install_ubuntu_lib32.sh
git add bin/ubu_setup_java8.sh
git add bin/gz2bz2.sh
git add bin/ddrescue_clone_in_fault_tolerant_way.sh
git add bin/howto_install_wordpress_on_ubuntu_13.04.sh
git add bin/rmlist.sh
git add bin/cp_wallpaper_launcher.sh
git add bin/set_build_env.sh
git add bin/delete_dup.py
git add bin/ubu_repo_install_docker_java.sh
git add bin/restore_all_mysqldatabases.sh
git add bin/fcitxsetup.sh
git add bin/repairgrub.sh
git add bin/bugzilla_bugzilla-4.2.1_go.sh
git add bin/batch_edit_grub_config.sh
git add bin/hangout_setup_1604.sh
git add bin/install_openstack_juno_on_ubuntu_14.10___single_machine_setup.sh
git add bin/gitinit.sh
git add bin/GBKsetup02.sh
git add bin/mount_all_share_disks.sh
git add bin/emacs_macbook_install.sh
git add bin/aptget_bzr_util.sh
git add bin/genlist.sh
git add bin/shell_usage_samples.sh
git add bin/fix_scratchbox_unknown_xterm_type.sh
git add bin/new_clean_makeall.sh
git add bin/scratchbox2_howto.sh
git add bin/enable_ftpd_in_ubuntu.sh
git add bin/x86go.sh
git add bin/curdir_adb_install_all_apk.sh
git add bin/allapk.sh
git add bin/adb_subdir_inst_all_apk.sh
git add bin/hi5_id_in_file.sh
git add bin/fonts.scale
git add bin/go30.arm.sh
git add bin/ins_pdf.sh
git add bin/gen_outdir_buildlist.sh
git add bin/subdir_github_android_build.sh
git add bin/send_a_SIGINFO_signal_to_dd_every_five_seconds_and_cause_it_to_print_its_progress_to_the_Terminal.sh
git add bin/upnp_init_step3.sh
git add bin/refresh_fstab_with_uuid_boot02.sh
git add bin/keep_order_uniq2.py
git add bin/find_localhost_ip.sh
git add bin/ec2rc.sh
git add bin/uuidgen__for_new_uuid__of_anydisk.sh
git add bin/down-get-pip.py.sh
git add bin/gen_github_key.sh
git add bin/mac_java8_install.sh
git add bin/dd_root_part_dev-sda11.sh
git add bin/mv_all_defect_list_tarball_to_new_drive.sh
git add bin/install_github_the_easiest_way.sh
git add bin/up_x11vnc.sh
git add bin/up_sshfs_on_remote_host.sh
git add bin/gen_public_der.sh
git add bin/vimrc
git add bin/cloudify_nodecellar_example_cfy_local.sh
git add bin/setup_ubuntu_proxy_server.sh
git add bin/django_inst_satchmo.sh
git add bin/make_c_h_tags.sh
git add bin/filename_GB_fix.sh
git add bin/all_outsider.sh
git add bin/back.sh
git add bin/yumseek.sh
git add bin/setenv_qt4.8.4.sh
git add bin/bigramfreq
git add bin/git-prompt.sh
git add bin/wget_google_via_proxy.sh
git add bin/github_cloudify_unzip_cloudify_nodecellar_openstack_puppet_standalone_master_go.sh
git add bin/apt-get-hfs.sh
git add bin/localconfig
git add bin/reset_alsa.sh
git add bin/substract_2_files.sh
git add bin/tor_client.sh
git add bin/wget_build_inst-gold-ld_in-binutils.sh
git add bin/wget_mindcraft_to_current_dir.sh
git add bin/python-apt_0.8.8ubuntu6.dsc
git add bin/setenv.sh
git add bin/du-h_home_vhuang.sh
git add bin/nosudo_cfy_local_openstack.sh
git add bin/ubuntu_inst_lamp.sh
git add bin/install_lib32.sh
git add bin/setup_tint2.sh
git add bin/apt-get-libqt4-dev
git add bin/etag_types.sh
git add bin/all_sd_disks_to_one_line.sh
git add bin/zipall.sh
git add bin/index_w_jieba.py
git add bin/untar_all_tgz.sh
git add bin/hosts_02
git add bin/bashrc-dell7710
git add bin/curdir_parse_code_goo_search_pages_and_svn_all.sh
git add bin/arm_quick_make_all.sh
git add bin/subdircleanarm.sh
git add bin/generated_manual_mount_all.sh
git add bin/bashrc-2012-02-12-10-20-54
git add bin/install_horizon.sh
git add bin/add_apt_repository_for_13.04.sh
git add bin/configure_make__overriding_cflag.sh
git add bin/subdircleanarm_gcc481.sh
git add bin/down_latest_android_n_tarball.sh
git add bin/topwords.sh
git add bin/mv_ls_lt_filelist_to_newdrive.sh
git add bin/subdir_git_syncall.sh
git add bin/namefreq
git add bin/upgrade_docker-compose.sh
git add bin/rubysetup.sh
git add bin/subdirquickarm.sh
git add bin/treesubdir.sh
git add bin/config
git add bin/setenv_qt484.sh
git add bin/gclient-go.sh
git add bin/subdir_gen_backup_domain_list.sh
git add bin/apache_start.sh
git add bin/subdir_find__AndroidManifest.xml_and__android_update__path_targetId_subprojects.py.backup
git add bin/subdir_unzip_all_7z.sh
git add bin/rename_all_fn.sh
git add bin/low
git add bin/wget_opencl_demo_n_run.sh
git add bin/android_sdk_update.sh
git add bin/cloudify_nodecellar_example_all.sh
git add bin/remove_n_reinstall_mysql.sh
git add bin/update_upnp
git add bin/mp3_filename_to_gbk2utf8.sh
git add bin/android20120515_http___source.android.com_source_downloading.html.downloaded_and_documented.sh
git add bin/gen_all_optbuild.sh
git add bin/build_qt3_x11_free.sh
git add bin/rackup
git add bin/post_via_wget.sh
git add bin/aptget_efl_pack.sh
git add bin/keep_order_uniq.py
git add bin/cp_all_java_has_main_to_jars_folder.sh
git add bin/docker_all_env_unset.sh
git add bin/init_cmake_kde.sh
git add bin/googim.py
git add bin/add_daniel_as_samba_user.sh
git add bin/newdocker.sh
git add bin/apt-get-libqt4-core
git add bin/spark_setup.sh
git add bin/down_py353.sh
git add bin/make_backup_list.sh
git add bin/x86conf.sh
git add bin/build_all_all_ndk_subdir_samples.sh
git add bin/all_tail.sh
git add bin/install_go_from_golang.org.sh
git add bin/repl_all_dns_to_ipaddr_in_file.py
git add bin/init.sh
git add bin/setup_webserver_v2.sh
git add bin/wget_gcc481.sh
git add bin/playonlinux.list
git add bin/firefox_profile.sh
git add bin/sublime-text3-ubuntu-install.sh
git add bin/testdisk.log
git add bin/install_opencl_pack.sh
git add bin/camera_setup.sh
git add bin/free_diskspace_for_google.py.sh
git add bin/prelibs_install_for_cheese_build.sh
git add bin/mp3tagiconv
git add bin/backup_all_mysql_db_to_curdir_db-mysql.sh
git add bin/qt-configure
git add bin/subdir_replace_oldstr_newstr.sh
git add bin/go_cpan.sh
git add bin/build_alsa.sh
git add bin/interative_debugged_setup_git_server_on_ubuntu.sh
git add bin/ruby_build.sh
git add bin/run_necessitas.sh
git add bin/git-commit-all.sh
git add bin/setup_mongodb.sh
git add bin/uuidgen__for_new_uuid__of_cloned_sda7.sh
git add bin/apt-cache_search_relative_given_keywords.sh
git add bin/ova2ovf.sh
git add bin/aptget_touch_support.sh
git add bin/preinstall_bugzilla02.sh
git add bin/tweek_ubuntu_aspire_touchpad.sh
git add bin/aptget_srp_depending_src02.sh
git add bin/move_apk_compiled_ok_dir.sh
git add bin/commoncrawl_all_downscript_from_warc_paths.sh
git add bin/wget_python2.sh
git add bin/install_unbuntu__desktop_on_server_w_alternate_cd_without_internet.sh
git add bin/ubuntu_setup_redmine20130701.sh
git add bin/html2text
git add bin/passwd0
git add bin/openport.sh
git add bin/x86_new_quick_makeall.sh
git add bin/install_jdk8.sh
git add bin/scratchbox_run-me-first_on_ubu10.10.sh
git add bin/subdir_shorten_fn_then_align.sh
git add bin/set_source_qt470_env.sh
git add bin/run_gunicorn.sh
git add bin/django_store_go.sh
git add bin/#setopt#
git add bin/outdirx86quick_build.sh
git add bin/setup_git_server_on_ubuntu.sh
git add bin/convert_sample.sh
git add bin/ins_bdb.sh
git add bin/ubuntu1404_sandbox_src_cloudify_cloudify_nodecellar_example_bs.sh
git add bin/get_google_search_url_list.sh
git add bin/ins-rvm-with_ruby-rails-puma.sh
git add bin/aptcach2get.sh
git add bin/cloudify_nodecellar_example_bs_cloudstack_blueprint.sh
git add bin/install_libs32.sh
git add bin/setup-xorg.sh
git add bin/rubygerm-etc-ubuntu-setup-script.sh
git add bin/touch-all.sh
git add bin/subdir_okapk_relativepaths.sh
git add bin/apt_get__doc_convert_packages.sh
git add bin/convert_vmx2ovf.sh
git add bin/centos_dev_init.sh
git add bin/init_all_for_unbuntu_11.10.sh
git add bin/gen_jarlist.sh
git add bin/install_64bit_mx330_driver.sh
git add bin/untar_all_redmine_disk_to_curdir.sh
git add bin/rm_all_redunt.sh
git add bin/etc_cron.weekly_dosftrim
git add bin/create_manual_UUID_mount_all_script.sh
git add bin/gowall2.sh
git add bin/ubuntu_install_mod_wsgi.sh
git add bin/convert_wav_to_mp3__installer.sh
git add bin/curdir_digout_cnet_appurl.sh
git add bin/github_clone.sh
git add bin/generating_ssh_public_private_keys.sh
git add bin/genopt_buildlist.sh
git add bin/toolchain_usecase03.sh
git add bin/victor_setenv.sh
git add bin/.goutputstream-O9JPRV
git add bin/fastGregAtHomeRamBootOnly.sh
git add bin/subdir_okapk_abspaths.sh
git add bin/tizen_install.sh
git add bin/dos_path
git add bin/wget03.sh
git add bin/google_hangout_install.sh
git add bin/customize_vnc_session.sh
git add bin/batch_jpg_resize.sh
git add bin/get_url_lists_in_html.sh
git add bin/gen_git_pull_all_list.sh
git add bin/vmware_restart.sh
git add bin/couch+django_intergration.sh
git add bin/init_sheepdog.sh
git add bin/cyg_ansible_setup.sh
git add bin/setup_rhomobile.sh
git add bin/gz2bgz_via_efficient_pipe.sh
git add bin/etc_apt_sources.list.backup
git add bin/ins_bind9.sh
git add bin/renwithtail
git add bin/wechaty-build.sh
git add bin/preinstall_analogix_util__for__8051.sh
git add bin/batch_gedit_fstab01.sh
git add bin/init_project.sh
git add bin/Using_scratchbox2_and_Ubuntu_11.10.sh
git add bin/compile_openssl_trial_openssl_1.0.1c.ok.sh
git add bin/aptget_all_i386.sh
git add bin/mdf
git add bin/subdir_find__AndroidManifest.xml_and__android_update__path_targetId_subprojects.py
git add bin/all_setup_ssh.sh.save.1
git add bin/tor-restart.sh
git add bin/setup_gstreamer_devs.sh
git add bin/setenv_qt5.sh
git add bin/install_scratchbox2.sh
git add bin/yumsearch
git add bin/unzip__to__subdir_unzip.sh
git add bin/daily_update_firefox.sh
git add bin/cfynew_run.sh
git add bin/7z_ins.sh
git add bin/install_satchmo.sh
git add bin/r75364-nightly-enable-all-build-chromium-with-runhooks.sh
git add bin/unity-tweak-tool-fix.sh
git add bin/hg_mecurial_support.sh
git add bin/sshhome.sh
git add bin/ins_touchpad_conf.sh
git add bin/working_download_setup_scratchbox.sh
git add bin/apt-get-cheese-n-build.sh
git add bin/normwget
git add bin/zpoolcreate.sh
git add bin/vbox_part_to_vdi.sh
git add bin/sb2_setup02.sh
git add bin/bigramcat
git add bin/detect_aptcache_of_no_package_found.sh
git add bin/reinstall_py.sh
git add bin/init_skype_apps.sh
git add bin/url_downed.py
git add bin/ln_target_path_to_here.sh
git add bin/linux_subdir_do__AndroidManifest.py
git add bin/cook
git add bin/ubuntu_install_wordpress.sh
git add bin/latest_working_generated_manual_mount_all.sh
git add bin/ln_allsubdir_to_home.sh
git add bin/ubu1404.5_gpg_keys.sh
git add bin/jumpstart_pinax_all_in_1.sh
git add bin/gen_unziplist.sh
git add bin/sshfs_on_topwire.sh
git add bin/mp3_gbk_setup.sh
git add bin/ubuntu_install_skype.sh
git add bin/curdir_level1_github_unzip_all_make_apk.sh
git add bin/gen_ziplist.sh
git add bin/lower_wordfreq_sort_gt2.sh
git add bin/git_first_run.sh
git add bin/setup_bugzilla_opt_plugin.sh
git add bin/tutorial.conf
git add bin/github_syncall.sh
git add bin/ins_tomcat.sh
git add bin/post_hadoop_hbase_build_config.sh
git add bin/camel_setup.sh
git add bin/CenOS_ins_lamp.sh
git add bin/wget02.sh
git add bin/hosts
git add bin/setup_nfs.sh
git add bin/lnall.sh
git add bin/unrar_all_tarball.sh
git add bin/add_hi5_id_wishlist_from_txtfile.sh
git add bin/UltraEdit_rightClick.reg
git add bin/down_all.sh
git add bin/ins_all_gstreamer_dev.sh
git add bin/cn.norm.sh
git add bin/apt-get-bzlib_n_setup.sh
git add bin/aptget_install_i386libs.sh
git add bin/stelvio_workspace_clone.sh
git add bin/gradle
git add bin/st-data=SaveChanges=Reboot
git add bin/allsubdir_list_has_dot_h.sh
git add bin/git_init_qemu.sh
git add bin/convert_multiple_png_to_pdf.sh
git add bin/batch_add__git_user_account.sh
git add bin/.txt
git add bin/pre_redmine.sh
git add bin/wget_vmware-server-n-build.sh
git add bin/dir_hiearch2import.sh
git add bin/setup_ubuntu_daa_to_iso__conversion.sh
git add bin/fuse_init_automount_etc.sh
git add bin/emails_in_file_ok.py
git add bin/switch_arm-linux-gnueabi.sh
git add bin/loop_subdir_backupdomain.sh
git add bin/pet_copypaste_to_up.sh
git add bin/curdir_apkmake.sh
git add bin/makewin32.sh
git add bin/downthemall_htm2py.sh
git add bin/subdir_backall_domain.sh
git add bin/norm.sh
git add bin/gitclone_nodecellar.sh
git add bin/ins_ubuntu_zip_tools.sh
git add bin/pinyin_sort_setup.sh
git add bin/controlpoint-build.sh
git add bin/ceph_step2.sh
git add bin/mark_all_badblocks_in_harddisk.sh
git add bin/cnfn.sh
git add bin/setup_pdf2txt_doc2txt.sh
git add bin/build-chromium-gold-SISO.sh
git add bin/remake.sh
git add bin/preins_mythtv.sh
git add bin/pythonsetup.sh
git add bin/setqt5.sh
git add bin/wf2pydict.sh.wf
git add bin/refresh_initramfs02.sh
git add bin/auto-indent-mode.el
git add bin/upnp_init_step2.sh
git add bin/inst_alsa_for_aspire-5552.sh
git add bin/sync_all.sh
git add bin/up
git add bin/outside_sbox-apt_get_svn_src.sh
git add bin/setenv_qt510.sh
git add bin/runme_in_mac_enable_disk_writable.sh
git add bin/gen_clingmv__to_lib_standalone_n_lib_jar.sh
git add bin/setup_scala.sh
git add bin/zfs_setup.sh
git add bin/adb_install_all_wallpapers.sh
git add bin/#w2.py#
git add bin/hiscap
git add bin/ins_redmine.sh
git add bin/add_qt5_ppa_on_ubuntu.sh
git add bin/victor-qt5.9-configure
git add bin/setopt.sh
git add bin/install__bugzilla.sh
git add bin/x86_quick_make_all_toolchains.sh
git add bin/generate_dir_4_UUID.sh
git add bin/install_ubuntu_pdf_editor.sh
git add bin/aptget_libqt3.sh
git add bin/git_pinax.sh
git add bin/sshfs_on_v114.sh
git add bin/manual_mount_all_raid_disks.sh
git add bin/lownorm.sh
git add bin/convert_subdir_examples_pro_mak_sln_to_batchmakes.py
git add bin/wget_nutch21.sh
git add bin/add_new_upnp_service_on_phone.sh
git add bin/all_install_satchmo02.sh
git add bin/uppercase_first_char_all_else_lowercase.sh
git add bin/disksmount.sh
git add bin/clean.sh
git add bin/subdiropt.sh
git add bin/ubuntu1404_sandbox_src_jason.sh
git add bin/django_build_satchmo_store.sh
git add bin/gziphead
git add bin/ubu_iphone_support.sh
git add bin/#setenv#
git add bin/configure_cmake_libminupnp_env.sh
git add bin/ubu_inst_hadoop_latest.sh
git add bin/plm_install-all-bugzilla3_n_4.sh
git add bin/cleanup_firefox_profile.ini.py.sh
git add bin/optmake
git add bin/digout_github_html_urllist.sh
git add bin/optset
git add bin/peeklist_in_dpkg-archive.sh
git add bin/mvall40.sh
git add bin/run_gitdown_shells.sh
git add bin/rdsmall.sh
git add bin/later_dpkg--forceoverwrite_for_gedit.sh
git add bin/subdirlist.sh
git add bin/git_clone__maven-android-sdk-deployer.git.sh
git add bin/cleanwf
git add bin/install_openjdk_jre_java.sh
git add bin/wget_lenny_glib2.sh
git add bin/git_build_gitosis.sh
git add bin/normalize_filename_4_orasearch.sh
git add bin/mp3cntag_update.sh
git add bin/inst_satchmo.sh.bat
git add bin/setenv
git add bin/gen_subdir_all.sh
git add bin/setup_libcgroup.sh
git add bin/victorset
git add bin/dot_emacs
git add bin/maven_init_generate.sh
git add bin/cache_proxy_list.sh
git add bin/ins_all_qt4-dev.sh
git add bin/virtualbox_set_uuid.sh
git add bin/digout_block_with_start_end_token.sh
git add bin/upgrade_to_next_version_of_ubuntu.sh
git add bin/bashrc_cygwin
git add bin/fix_docker.sh
git add bin/bootrepair.sh
git add bin/subdir_find_build.xml_n_build.py
git add bin/install_mesa.sh
git add bin/txt_wordfreq_delim_stat.sh
git add bin/tar_all_subdirs.sh
git add bin/rm_all_docker_container.sh
git add bin/wget__androidBoard___patchs.txt.sh
git add bin/docker-ip
git add bin/normalize_curdir_txt_filename.sh
git add bin/samba_commandline.sh
git add bin/redhat_vnc_client.sh
git add bin/itune_on_ubuntu.sh
git add bin/setup_pyqt.sh
git add bin/build_PyQt410_n_install.sh
git add bin/cloudify_docker_plugin_pip_docker_py.sh
git add bin/set_env.sh
git add bin/install-maemo_n_sb2.sh
git add bin/cleanup_firefox_profile.ini.py
git add bin/ldap_client_setup.sh
git add bin/push_itune_music_to_android_phone_with_adb.sh
git add bin/rename_curdir_nov2015_commoncraw_to_shorter_fn.sh
git add bin/beijing_svn_server.sh
git add bin/stamp_to_victor_log.sh
git add bin/cloudify_nodecellar_example_go2.sh
git add bin/all_mkdir.sh
git add bin/phonenum_in_file.sh
git add bin/insbox_max_init_sbox_src.sh
git add bin/install_all_google_engines.sh
git add bin/batch_launch_chrome_multitab_for_id_list_from_txtfile.sh
git add bin/bwquote
git add bin/stelvio_root_init.sh
git add bin/jake_setup.sh
git add bin/wf2wfdir
git add bin/install_latest_firefox.sh
git add bin/man2txt.sh
git add bin/android_src_setup.sh
git add bin/snapshot.sh
git add bin/filter_by_stopwords.py
git add bin/install_oracle_java8.sh
git add bin/resolv.conf.backup02
git add bin/bootstrap_qt57.sh
git add bin/inst_satchmo.sh
git add bin/how-to-install-ghost-on-ubuntu.sh
git add bin/ins_build32_env_for_android_src2.1-step02.sh
git add bin/ubuntu1404_sandbox_src_go.sh
git add bin/devstack_gitrun.sh
git add bin/fonts.dir
git add bin/setup_ld_in_binutils.sh
git add bin/apt-get-cmake-qmake.sh
git add bin/ccrawl_only_defect_list.sh
git add bin/repair_boot.sh
git add bin/bashrc-2012-07-19-15-52-27
git add bin/subdir_git_apk.sh
git add bin/checkout_r78965_n_build.sh
git add bin/copy_arm7v_ffmeg_so_files__to_here.sh
git add bin/umount_all_remote.sh
git add bin/run_nexus7.sh
git add bin/apache_stop.sh
git add bin/aptget_scrapy_pack.sh
git add bin/gen_tarlist.sh
git add bin/wget_mx330_scanner_printer_x86_64.sh
git add bin/Installing_scratchbox_1_and_2_for_ARM_cross-compilation.sh
git add bin/install-chrome.sh
git add bin/ins_java7.sh
git add bin/subdir_get_all_proxylist.py
git add bin/subdircleanx86.sh
git add bin/make_UUID_into_fstab.sh
git add bin/libunwind_1.0.1-4ubuntu2.dsc
git add bin/backup_Nandroid.sh
git add bin/find_err_difs.sh
git add bin/split_shell_to_equal_lines.sh
git add bin/bayvictor_gitconfig.sh
git add bin/subdir_shorten_pictures_fn.sh
git add bin/perl_cpan_install.sh
git add bin/mkdir_for_mount_points.sh
git add bin/reinit_createdownframe_for_all_subdir.sh
git add bin/ins_build32_env_for_android_src2.1.sh
git add bin/ins_eclipse_pack.sh
git add bin/gitclone.sh
git add bin/nosudo_down_blueprint.sh
git add bin/cloudify_nodecellar_example_local_ins.sh
git add bin/docker_cleanup.sh
git add bin/wget_android_bundle.sh
git add bin/jieba_len.word.desc.py
git add bin/initread
git add bin/tagandroid.sh
git add bin/git_all_pinax.sh
git add bin/preinstall_redmine02.sh
git add bin/gedit_cn_fix.sh
git add bin/git_add_push_all.sh
git add bin/inside_scratchbox_python-build_even_for_opt_media_local.sh
git add bin/replace_all_strings_in_subdirfiles
git add bin/gnome_reset.sh
git add bin/tor_install.sh
git add bin/schedule_cron_backup_for_mysql.sh
git add bin/set_joycrawler_env.sh
git add bin/git_config.sh
git add bin/aptpack.sh
git add bin/repo
git add bin/apk_time_rank.sh
git add bin/mv_vmx_to_sda354.sh
git add bin/locate_n_clone_all_fileformat_to_curdir.sh
git add bin/install_lvm.sh
git add bin/git_update_pull_all.sh
git add bin/run.sh
git add bin/git_all_py_nosql_frameworks.sh
git add bin/add_root_account.sh
git add bin/libz_init.sh
git add bin/install_wallpaper_changer_variety.sh
git add bin/get_mindmap_mm_from_mundstein.sh
git add bin/w1freqge3bare.sh
git add bin/timestamp
git add bin/wget_extra.sh
git add bin/dot_emacs_config
git add bin/setup_automake_autoconf.sh
git add bin/inside.sh
git add bin/setup_qt5.sh
git add bin/go32.sh
git add bin/all_install_satchmo.sh
git add bin/aptget_install_qemu_etc.sh
git add bin/gitpush.sh
git add bin/manual-mount_all.sh
git add bin/preinstall_bugzilla.sh
git add bin/police.py
git add bin/bestway_setup_satchmo.sh
git add bin/bashrc-2013-08-06-11-17-49
git add bin/2012__0514_github_server__setup.sh
git add bin/py35
git add bin/rdesk.sh
git add bin/add_myself_to_docker_group.sh
git add bin/install_all_openstack.sh
git add bin/go30.02.sh
git add bin/clone_old-scratchbox_over.sh
git add bin/install_rvm_ubunbu14.04.sh
git add bin/copy_subdir_files_to__flat__dir.sh
git add bin/set_arm_sb2_env.sh
git add bin/trusty_GB_term_convmv.sh
git add bin/install_webgl_editors.sh
git add bin/bashrc-2012-02-12-10-15-41
git add bin/hislog.sh
git add bin/down_n_build_android4.0.sh
git add bin/clean
git add bin/bugzilla_wget_bugzilla.sh
git add bin/#normalize_path.sh#
git add bin/easyinstall_ansible.sh
git add bin/unzipall.sh
git add bin/setup_root_login_gui.sh
git add bin/curdir_mv2dir.sh
git add bin/grabix
git add bin/mv_list_to_sda354.sh
git add bin/samsung-sdk-init.sh
git add bin/go30.sh
git add bin/install_all_magick.sh
git add bin/build-chromium-without-runhooks.sh
git add bin/wordfreq
git add bin/test03.py
git add bin/git_clone_encr_py.sh
git add bin/removeall_pulseaudio.sh
git add bin/maemo-sdk-install_5.0.sh
git add bin/.setup_git_server_on_ubuntu.sh.swo
git add bin/geckodriver
git add bin/reinstall_grub_on_sda11.sh
git add bin/git_gateone.sh
git add bin/subdir_github_alldirlevel_unzip_make_apk.sh
git add bin/backup_curdir_all.sh
git add bin/oneStack.sh
git add bin/github_cloudify_unzip_go.sh
git add bin/etc_environment
git add bin/build_cvs_server.sh
git add bin/vhuang_cvs_login.sh
git add bin/pure_zh_cn_GBK_env.sh
git add bin/Install_Subversion_with_Web_Access_on_Ubuntu.sh
git add bin/10mv_sudirfiles_here.sh
git add bin/build-binutils-32bit.sh
git add bin/html2py.sh
git add bin/aptbag.sh
git add bin/subdir_replace_android_app_name.sh
git add bin/config_rhythmbox_as_dlna.sh
git add bin/upnp_init_step4.sh
git add bin/000-default
git add bin/dta_shorten_fn.sh
git add bin/ins_libcv_etc.sh
git add bin/github_go.sh
git add bin/ndkgo.sh
git add bin/essentials.sh
git add bin/adt-ndk-buildup.sh
git add bin/install_ubuntu_jenkins.sh
git add bin/aptget_ftjam_jam.sh
git add bin/install_xcb_stuffs.sh
git add bin/test_tor.sh
git add bin/subdirquickx86.sh.old
git add bin/add_missing_aptkey.sh
git add bin/build_subdir_resumable_apk.sh
git add bin/make_manual_mount_shell
git add bin/install_py_pip.sh
git add bin/add_apt_repository_for_12.4.sh
git add bin/w2.py
git add bin/rename_indir_ui.html_to_ui.sh
git add bin/ins_valgrind.sh
git add bin/install_gui_on_ubuntu_server.sh
git add bin/all_chown.sh
git add bin/killall.sh
git add bin/subdir_okapk_dirs.sh
git add bin/cloudify_manager_blueprints_simple.sh
git add bin/setting_pu_sb2_from_scratch_with_raspberry_pi.sh
git add bin/github_update_all.sh
git add bin/tieba_fn_GB.sh
git add bin/install.deb.sh
git add bin/cfynew_inside_bootup.sh
git add bin/setup-java8.sh
git add bin/autobuild.sh
git add bin/ins_scim.sh
git add bin/migrate_from_redmine_to_zoicbox.sh
git add bin/subdir_level1_tag_github_syncall.sh
git add bin/newnorm.sh
git add bin/adb_install_all_subdir_apk.sh
git add bin/convoy_setup.sh
git add bin/checkout_pybing.sh
git add bin/mv_giga_file_to_curdir.sh
git add bin/make_all_sshfs_for_outsiders.sh
git add bin/compiz_reset_to_default.sh
git add bin/Uninstaller.manifest
git add bin/pudb.sh
git add bin/umount_dir_4_UUID.sh
git add bin/13.10.sources.list
git add bin/lower.sh
git add bin/gitCommitExistProj.sh
git add bin/find_setuid_bin.sh
git add bin/rmall_google_empty_dirs.sh
git add bin/install_cobbler.sh
git add bin/init_cygwin_git_stanch_cert.sh
git add bin/install_ror.sh
git add bin/subdircleanx86.sh.old
git add bin/wget_n_build_arm_mplay.sh
git add bin/pkg_config_lib_ver.sh
git add bin/fix_control_caplock_sync_in_x.sh
git add bin/cmd_line_eclipse_build.sh
git add bin/ubuntu_LAMP_install.sh
git add bin/rebuild_dpkg.sh
git add bin/configure-qt4-into-arm.sh
git add bin/wallpaper_changer_for_ubuntu_variety.sh
git add bin/install.docker.sh
git add bin/subdir_github_url.sh
git add bin/__etc_apache2_sites_enabled_000_default
git add bin/setup_alsa-lib-1.0.16.sh
git add bin/outdirbuild.sh
git add bin/stamp_all_android_appname.sh
git add bin/oracle_precheck.sh
git add bin/unzip_all_7z.sh
git add bin/subdir_android_git_build_all.sh
git add bin/tor_restart.sh
git add bin/curdir_normall.sh
git add bin/align_quote_text.sh
git add bin/job_backup_unrar_all.sh
git add bin/xml_validator.sh
git add bin/gen_ndk_clean_build.py
git add bin/apt_get_all_ia32lib.sh
git add bin/subdir_resume_make_debug_apk.py.debug
git add bin/.bashrc
git add bin/deb_dpkg_cloudify_cli.sh
git add bin/android_dev_setupall.sh
git add bin/zh
git add bin/py27
git add bin/auto_install_vmware_packages.sh
git add bin/sudo_mkdir_for_raid.sh
git add bin/qt-configure.sh
git add bin/reverse_any_list.sh
git add bin/subdir_gitdown_keyword_hits2.sh
git add bin/ubuntu1404_sandbox_cloudify_manager_cloudify_manager_blueprints_cpalljson.sh
git add bin/aptget_ocr.sh
git add bin/sb2arm.sh
git add bin/pack_jpg_to_new_pdf_name.sh
git add bin/init_project-2012-05-29-19-14-02.txt.sh
git add bin/bare
git add bin/gitclone_pyvcloud_cloudify_docker_plugin.sh
git add bin/ins_bzr.sh
git add bin/all_setup_ssh.sh
git add bin/digout_hi5id.sh
git add bin/swap_control_key_n_caplock.sh
git add bin/output.ps
git add bin/ffmpeg.sh
git add bin/bashrc02
git add bin/upnecessitas.sh
git add bin/untar_ss_sdk_scratchbox.sh
git add bin/ubu_dev_upgrade.sh
git add bin/apt-get_source_subversion_n_build.sh
git add bin/run_secure_vnc.sh
git add bin/ln_all_home_to_bigbase.sh
git add bin/gen_spend_report.wellsfargo.csv.sh
git add bin/www.sh
git add bin/outdirx86libtool_build.sh
git add bin/victor_saved_logs
git add bin/all_gimp.sh
git add bin/xcodebuild.sh
git add bin/scala_setup.sh
git add bin/bat_grub_edit.sh
git add bin/normalizedly_down_urllist.sh
git add bin/victor-dpkg-for-SLP-scratchbox-components.sh
git add bin/round_bracket_escaping.sh
git add bin/install_hathor_deb.sh
git add bin/RenamefilestocopyfromLinux.sh
git add bin/install_pdf_editor.sh
git add bin/apt_get_all_movie_plugins.sh
git add bin/install_skype_under_ubuntu14.04.sh
git add bin/wget_latest_qemu.sh
git add bin/redo
git add bin/bzr_init_all.sh
git add bin/test.txt.sh
git add bin/subdir_normalize_shell__n__cp_to_bin_dir.py
git add bin/setup_ubuntu_console_gui__filemanagers.sh
git add bin/setup_flash.sh
git add bin/bugzilla_postgres_go.sh
git add bin/installing_the_canonical_distribution_of_ubuntu_openstack.sh
git add bin/police.sh
git add bin/start_fink.sh
git add bin/git_ffmpeg.sh
git add bin/cloudfoundry_setup.sh
git add bin/restartx.sh
git add bin/aptget_subversion_packages.sh
git add bin/upmedia
git add bin/makeexe.sh
git add bin/atareao-updf-trusty.list
git add bin/make_all_toolchain.sh
git add bin/ndk_curdir.sh
git add bin/github_repo_url_from_html_saved.sh
git add bin/setup_apache_12102010.sh
git add bin/backup_domain.sh
git add bin/subdir_extract_github_ziplist.sh
git add bin/fstab_auto_mount_remote_sshfs.sh
git add bin/cheader_etags.sh
git add bin/normget
git add bin/apt_get_scratchbox.sh
git add bin/docker-upgrade.sh
git add bin/top40word.sh
git add bin/ins_fast.track.sh
git add bin/install_vmware_server_on_ubuntu__with_ubu910_patch.sh
git add bin/presetup.sh
git add bin/hosting_git_repositories__the_easy__and_secure__way.sh
git add bin/flatly_clone_all_fileext_to_subdir.sh
git add bin/sshfs_on_dell7710.sh
git add bin/rvm_ubuntu_setup.sh
git add bin/subdir_resume_make_debug_apk.py
git add bin/rm_large.sh
git add bin/vagrant_setup.sh
git add bin/ins_boost_4_k3d.sh
git add bin/test033.py
git add bin/gitcoa.sh
git add bin/install_evolution_packages.sh
git add bin/skype_setup_1604.sh
git add bin/ubu_install_redmine.sh
git add bin/add_vhuang_as_samba_user.sh
git add bin/x86_clean_make_all.sh
git add bin/m4a2mp3.sh
git add bin/aptget_qemus.sh
git add bin/curdir_all_html2txt_py.sh
git add bin/ubuntu_install_sogou.sh
git add bin/install_puppet_14.04.sh
git add bin/github_down_n_gen_most_stars_ranking.py
git add bin/delimfreq
git add bin/google_parse_xls_links.sh
git add bin/github_down_n_gen_most_stars_ranking.sh
git add bin/yum-install-all.sh
git add bin/linkedin_friend_norm.sh
git add bin/github_down.py
git add bin/apache_restart.sh
git add bin/normalize_path.sh
git add bin/cpall.sh
git add bin/subdir_images2pdf.sh
git add bin/scratchbox-network-enabler.sh
git add bin/outdirarmquick_build.sh
git add bin/bashrc2
git add bin/zpooldev.sh
git add bin/subdir_find.buggy.py
git add bin/pre_neccesitas.sh
git add bin/keep_order_uniq_w2.py
git add bin/buildall_subdir_github_tier1.sh
git add bin/ssh-copy-id-batch.sh
git add bin/cleanbrow.sh
git add bin/extract_proxylist.sh
git add bin/find_AndroidManifest.xml_and_adb_update_project.sh
git add bin/gen_github_down_sh.sh
git add bin/top_wordfreq.sh
git add bin/trusty_all_i386.sh
git add bin/xmodmap
git add bin/ModuleInfo.xml
git add bin/install_3d_editor.sh
git add bin/github_down_1_key.sh
git add bin/howto_Subversion_support_for_Bazaar_on_CentOS_5_.sh
git add bin/ins_googlepinyin.sh
git add bin/setup_mysql.connector.sh
git add bin/go3.libtool242.sh
git add bin/sbox64_hathor_setup.sh
git add bin/install_ime_google_pinyin.sh
git add bin/install-essentials.sh
git add bin/update_opensso_war.sh
git add bin/filter_stopword.sh
git add bin/gpackdir
git add bin/how_to_configure_nfs__network_file_system__on_ubuntu.sh
git add bin/gmp_5.0.5+dfsg-2ubuntu3.dsc
git add bin/all_tarball_for_subdirs.sh
git add bin/wf2pydict.sh
git add bin/fsck_all.sh
git add bin/install_mtouche_to_hardware_by_Victor.sh
git add bin/new_samba_setup.sh
git add bin/run_xrdp_server.sh
git add bin/django_satchmo_satchmo_projects_skeleton_go.sh
git add bin/automake1.11_1.11.6-1ubuntu1.dsc
git add bin/install_im_pidgin__for__ubuntu.sh
git add bin/init_adwords-py.sh
git commit -m "try recover deleted files"
git pull
git push

